# Generated by Django 4.2.7 on 2023-12-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingApp', '0002_bid_category_item_delete_customuser_bid_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='Default Item Name', max_length=255),
        ),
    ]
