# Generated by Django 4.2.6 on 2023-12-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BiddingApp", "0004_alter_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(default="Default Name", max_length=255),
        ),
        migrations.AlterModelTable(
            name="bid",
            table="Bid",
        ),
    ]
