# Generated by Django 4.2.6 on 2023-12-06 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("BiddingApp", "0005_alter_item_name_alter_bid_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
