# Generated by Django 4.2.6 on 2023-11-28 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="admin_pics/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("picture", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(max_length=255)),
                ("condition", models.CharField(db_column="Cond", max_length=255)),
                ("starting_price", models.IntegerField()),
                ("end_date", models.DateTimeField()),
                ("start_date", models.DateTimeField()),
            ],
            options={
                "db_table": "Item",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("Bank Transfer", "Bank Transfer"),
                            ("Cash", "Cash"),
                            ("Card", "Card"),
                        ],
                        max_length=15,
                    ),
                ),
                ("transaction_date", models.DateField()),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In Progress", "In Progress"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("payment_details", models.CharField(blank=True, max_length=255)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("Seller", "Seller"), ("Buyer", "Buyer")], max_length=6
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ViewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "item",
                    models.ForeignKey(
                        db_column="ItemID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bidding.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bidding.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("content", models.TextField()),
                (
                    "reviewee",
                    models.ForeignKey(
                        db_column="RevieweeID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_reviews",
                        to="bidding.user",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        db_column="ReviewerID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_reviews",
                        to="bidding.user",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        db_column="TransactionID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bidding.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField()),
                ("status", models.CharField(max_length=255)),
                ("total_amount", models.IntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        db_column="ItemID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bidding.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bidding.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        db_column="ReceiverID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="bidding.user",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        db_column="SenderID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="bidding.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_status", models.CharField(max_length=255)),
                ("estimated_delivery_date", models.DateField()),
                (
                    "order",
                    models.ForeignKey(
                        db_column="OrderID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bidding.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("status", models.CharField(max_length=255)),
                (
                    "item",
                    models.ForeignKey(
                        db_column="ItemID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bidding.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bidding.user",
                    ),
                ),
            ],
        ),
    ]
