# Generated by Django 4.2.6 on 2023-11-28 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bidding", "0001_initial"),
    ]

    operations = []
