# Generated by Django 4.2.6 on 2023-11-28 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bidding", "0002_auto_20231128_0417"),
    ]

    operations = []
